### ISSUE TITLE
ClassNotFoundException: controllers.ReverseController

### ISSUE THREAD

**Issue by travelstep** [edulify/play-sitemap-module.edulify.com#20]
Hi, 

I am getting a ClassNotFoundException using your Play Sitemap module. Using both annotation and sitemap providers.

Play version: 2.3.10
Scala version: 2.11.1
Sitemap version: 1.1.8
IDE: IntelliJ

I appreciate some help in this matter. 

Stacktrace: 

java.lang.ClassNotFoundException: controllers.ReverseApplication$
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_60]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_60]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_60]
        at com.edulify.modules.sitemap.AnnotationUrlProvider.actionUrl(AnnotationUrlProvider.java:58) [sitemapper_2.11-1.1.8.jar:1.1.8]
        at com.edulify.modules.sitemap.AnnotationUrlProvider.addUrlsTo(AnnotationUrlProvider.java:32) [sitemapper_2.11-1.1.8.jar:1.1.8]
[error] application - Package controllers does not have such class

Thank you!

BR

Christer

**Comment by megazord** [comment]
Hello @travelstep, 

Could you please submit a test application that reproduces this problem?

Thanks!

**Comment by travelstep** [comment]
Hi,

The problem occurs when using the Sitemap annotation combined with Scala. Solved it by removing the annotations. 

Thanks!
