### ISSUE TITLE
Listen to ApplicationLifecycle addStopHook

### ISSUE THREAD

**Issue by eximius313** [edulify/play-sitemap-module.edulify.com#22]
As [this](https://github.com/akka/akka/issues/16495) issue states, Akka can invoke scheduled task even though application has initiated STOP sequence. If one is using EntityManager, this causes nasty exception:
```
java.lang.IllegalStateException: EntityManagerFactory is closed
        at org.hibernate.jpa.internal.EntityManagerFactoryImpl.validateNotClosed(EntityManagerFactoryImpl.java:388)
        at org.hibernate.jpa.internal.EntityManagerFactoryImpl.internalCreateEntityManager(EntityManagerFactoryImpl.java:342)
        at org.hibernate.jpa.internal.EntityManagerFactoryImpl.createEntityManager(EntityManagerFactoryImpl.java:313)
        at play.db.jpa.DefaultJPAApi.em(DefaultJPAApi.java:71)
        at play.db.jpa.DefaultJPAApi.withTransaction(DefaultJPAApi.java:123)
        at play.db.jpa.DefaultJPAApi.withTransaction(DefaultJPAApi.java:80)
        at play.db.jpa.JPA.withTransaction(JPA.java:127)
        at controllers.sitemaps.SitemapUrlProvider.addUrls(SitemapUrlProvider.java:58)
        at com.edulify.modules.sitemap.SitemapTask.run(SitemapTask.java:35)
        at akka.actor.LightArrayRevolverScheduler$$anon$2$$anon$1.run(Scheduler.scala:242)
        at akka.actor.LightArrayRevolverScheduler$TaskHolder.run(Scheduler.scala:476)
        at akka.actor.LightArrayRevolverScheduler$$anonfun$close$1.apply(Scheduler.scala:282)
        at akka.actor.LightArrayRevolverScheduler$$anonfun$close$1.apply(Scheduler.scala:281)
        at scala.collection.Iterator$class.foreach(Iterator.scala:742)
        at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
        at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
        at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
        at akka.actor.LightArrayRevolverScheduler.close(Scheduler.scala:280)
        at akka.actor.ActorSystemImpl.stopScheduler(ActorSystem.scala:689)
        at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply$mcV$sp(ActorSystem.scala:618)
        at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply(ActorSystem.scala:618)
        at akka.actor.ActorSystemImpl$$anonfun$liftedTree2$1$1.apply(ActorSystem.scala:618)
        at akka.actor.ActorSystemImpl$$anon$3.run(ActorSystem.scala:642)
        at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.runNext$1(ActorSystem.scala:809)
        at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.apply$mcV$sp(ActorSystem.scala:812)
        at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.apply(ActorSystem.scala:805)
        at akka.actor.ActorSystemImpl$TerminationCallbacks$$anonfun$run$1.apply(ActorSystem.scala:805)
        at akka.util.ReentrantGuard.withGuard(LockUtil.scala:15)
        at akka.actor.ActorSystemImpl$TerminationCallbacks.run(ActorSystem.scala:805)
        at akka.actor.ActorSystemImpl$$anonfun$terminationCallbacks$1.apply(ActorSystem.scala:639)
        at akka.actor.ActorSystemImpl$$anonfun$terminationCallbacks$1.apply(ActorSystem.scala:639)
        at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
        at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply$mcV$sp(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at akka.dispatch.BatchingExecutor$BlockableBatch$$anonfun$run$1.apply(BatchingExecutor.scala:91)
        at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:72)
        at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:90)
        at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
        at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(AbstractDispatcher.scala:397)
        at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
        at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
        at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
        at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```
What you need to do is to inject ```ApplicationLifecycle``` and add a stopHook: 
```
private boolean stopped = false;
@Inject
public MyClass(ApplicationLifecycle lifecycle){
	lifecycle.addStopHook(() -> {
	        stopped=true;
	        return F.Promise.pure(null);
	});
}

@Override
public void run() {
	if(stopped == false){
		execute();
	}
}
```

**Comment by KarelCemus** [comment]
+1 for this, I also encounter this issue with 2.1.0 version using Play Scala and Squeryl

**Comment by eximius313** [comment]
Change ```com.edulify.modules.sitemap.SitemapTask``` to:
```
public class SitemapTask implements Runnable {

    private SitemapConfig sitemapConfig;
    private SitemapProviders sitemapProviders;
	private boolean stopped = false;
	
    @Inject
    public SitemapTask(SitemapConfig sitemapConfig, SitemapProviders providers, ApplicationLifecycle lifecycle) {
        this.sitemapConfig = sitemapConfig;
        this.sitemapProviders = providers;
		lifecycle.addStopHook(() -> {
			this.stopped = true;
			return CompletableFuture.completedFuture(null);
		});
    }

    @Override
    public void run() {
		if(stopped){
			return;
		}
        String baseUrl = sitemapConfig.getBaseUrl();
        String baseDir = sitemapConfig.getBaseDir();
        if (baseDir == null) {
            // This should be removed in a next release and an Exception
            // will be thrown when baseDir is not configured.
            baseDir = Play.application().getFile("public").getAbsolutePath();
        }
        try {
            WebSitemapGenerator generator = new WebSitemapGenerator(baseUrl, new File(baseDir));
            List<UrlProvider> providers = sitemapProviders.getProviders();
            for (UrlProvider urlProvider : providers) {
                urlProvider.addUrlsTo(generator);
            }
            generator.write();
            try {
                generator.writeSitemapsWithIndex();
            } catch (RuntimeException ex) {
                play.Logger.warn("Could not create sitemap index", ex);
            }
        } catch(MalformedURLException ex) {
            play.Logger.error("Oops! Can't create a sitemap generator for the given baseUrl " + baseUrl, ex);
        }
    }
}
```
This shoud help

**Comment by KarelCemus** [comment]
Just working on it, you saved me some time. Thanks!

**Comment by KarelCemus** [comment]
@eximius313 You posted nice solution but it should be accepted by the library. As temporary solution it requires either custom compilation of this library or modification of many classes. There is simple workaround, which does not require recompilation of this library. It just uses custom Play module and task wrapper.

There is Scala code:

```scala
package module.sitemap

import javax.inject.{Inject, Singleton}

import scala.concurrent.Future
import scala.concurrent.duration.{Duration, FiniteDuration}

import play.api.inject.ApplicationLifecycle

import akka.actor.ActorSystem
import com.edulify.modules.sitemap.{SitemapConfig, SitemapProviders, SitemapTask}
import com.google.inject.AbstractModule

class SitemapModule extends AbstractModule {
  protected def configure( ) {
    bind( classOf[ SitemapConfig ] ).asEagerSingleton( )
    bind( classOf[ SitemapProviders ] ).asEagerSingleton( )    
    bind( classOf[ BugfixingSitemapJob ] ).asEagerSingleton( ) // Note: changed from SitemapJob
  }
}

@Singleton
class BugfixingSitemapJob @Inject() ( actorSystem: ActorSystem, config: SitemapConfig, task: SitemapTask, lifecycle: ApplicationLifecycle) {

  private var running = true

  // disable when system is shutting down
  lifecycle.addStopHook( ( ) => Future( running = false ) )

  implicit val executionContext = actorSystem.dispatchers.lookup( config.getDispatcherName )

  actorSystem.scheduler.schedule(
    Duration.create( config.getInitialDelay ).asInstanceOf[ FiniteDuration ],
    Duration.create( config.getExecutionInterval ).asInstanceOf[ FiniteDuration ],
    new BugfixingTask // Note: use task wrapper instead
  )

  class BugfixingTask extends Runnable {
    // Note: delegate to the original task when the system is running
    override def run( ): Unit = if ( running ) task.run( )
  }
}
```

**Comment by marcospereira** [comment]
Do you mind submitting a pull request to solve this issue?

**Comment by eximius313** [comment]
@marcospereira will you release a new version?
