### ISSUE TITLE
Duplicate Mappings - Conflict with sbtWeb 

### ISSUE THREAD

**Issue by michalzubkowicz** [edulify/play-sitemap-module.edulify.com#27]
Only in test mode (./activator test) 
Such errors occur. I have no idea what is a reason.

`	project/target/web/public/test/public/lib/sitemap-module/stylesheets/main.css
from
	project/target/web/web-modules/test/webjars/lib/sitemap-module/stylesheets/main.css
		project/target/web/web-modules/test/webjars/lib/project5/lib/sitemap-module/stylesheets/main.css
	at scala.sys.package$.error(package.scala:27)
	at sbt.Sync$.noDuplicateTargets(Sync.scala:67)
	at sbt.Sync$$anonfun$apply$1.apply(Sync.scala:25)
	at sbt.Sync$$anonfun$apply$1.apply(Sync.scala:22)
	at com.typesafe.sbt.web.SbtWeb$.syncMappings(SbtWeb.scala:511)
	at com.typesafe.sbt.web.SbtWeb$$anonfun$34.apply(SbtWeb.scala:304)
	at com.typesafe.sbt.web.SbtWeb$$anonfun$34.apply(SbtWeb.scala:304)
	at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
	at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:40)
	at sbt.std.Transform$$anon$4.work(System.scala:63)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:226)
	at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:17)
	at sbt.Execute.work(Execute.scala:235)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:226)
	at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
	at sbt.CompletionService$$anon$2.call(CompletionService.scala:28)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[error] (web-assets-test:assets) Duplicate mappings:
[error] 	project/target/web/public/test/public/lib/sitemap-module/stylesheets/main.css
[error] from
[error] 	project/target/web/web-modules/test/webjars/lib/sitemap-module/stylesheets/main.css
[error] 		project/target/web/web-modules/test/webjars/lib/project5/lib/sitemap-module/stylesheets/main.css
[error] Total time: 11 s, completed Apr 28, 2016 4:47:16 PM
`

**Comment by marcospereira** [comment]
Try with version 2.1.1.
