### ISSUE TITLE
This is working with Scala ?

### ISSUE THREAD

**Issue by n0tel** [edulify/play-sitemap-module.edulify.com#4]
I tried it with Scala.
`UrlProvider` works as a Java version (see https://github.com/blabluble/play-sitemap-module/issues/3 )
But `@SitemapItem` annotation return the following error:

```
[error] application - Package controllers does not have such class
java.lang.ClassNotFoundException: controllers.ReverseApplication$
        at java.net.URLClassLoader$1.run(URLClassLoader.java:366) ~[na:1.7.0_25]

        at java.net.URLClassLoader$1.run(URLClassLoader.java:355) ~[na:1.7.0_25]

        at java.security.AccessController.doPrivileged(Native Method) ~[na:1.7.0
_25]
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354) ~[na:1.7.0
_25]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.7.0_25]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.7.0_25]
sitemap generator
```

sitemap.xml also generated, but creates unnecessary node
```
<url>
    <loc>http://example.comnull</loc>
    <changefreq>daily</changefreq>
    <priority>0.5</priority>
</url>
```

**Comment by dengalepirat** [comment]
@n0tel Yes they do, but you have to do it by using providers. Thats how I made it work.

**Comment by eximius313** [comment]
should this issue be still open?

**Comment by n0tel** [comment]
@eximius313  I don't use play-sitemap-module for now. So, it can be closed.
